/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class solarsitingucsc_smartsolarsiting_Controller_NativePanorama */

#ifndef _Included_solarsitingucsc_smartsolarsiting_Controller_NativePanorama
#define _Included_solarsitingucsc_smartsolarsiting_Controller_NativePanorama
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     solarsitingucsc_smartsolarsiting_Controller_NativePanorama
 * Method:    processPanorama
 * Signature: ([JJ)V
 */
JNIEXPORT void JNICALL Java_solarsitingucsc_smartsolarsiting_Controller_NativePanorama_processPanorama
    (JNIEnv *, jclass, jlongArray, jlong);

#ifdef __cplusplus
}

#endif
#endif
